---
title: "The accumulate_function"
author: "Isaac M-V"
date: "11/30/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

The accumulate() function comes from the purrr package. 
```{r cars}
library(purrr)
```


Accumulate() keeps doing the same function over and over and over again:
```{r pressure, echo=FALSE}
# Here we load the vector letters:
letters

# Here we apply the function paste to every element of the vector letter, over and over again, so the result of it is a Pascal triangle. 
accumulate(letters, paste)

# Here we multiple by 2 the new elements each time, 10 times.
accumulate(1:10, ~ 2*., .init = 1) #  ~ is the equivalent of function(.), .init means initial value, repeated 10 times. 

# Here we square the values:
accumulate(1:10, ~. ^2, .init = 2)

```


Pascal's triangle:
```{r}
row <- c(1,3,3,1)

c(0,row) + c(row, 0)

#Here we create the Pascal triangle. The initial value is 1, then 1 and 1. The symbol . represents the vector that is being generated at the end of each iteration and being used in the following iteration.
accumulate(1:6, ~c(0,.) + c(.,0), .init = 1)

```
